import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';

import Box from '@mui/material/Box';
import Typography from '@mui/material/Typography';

import styles from '@/styles/Home.module.scss';
import PrimaryLogo from '@/theme/icons/PrimaryLogo';
import CenteredFlexContainer from '@/components/UI/CenteredFlexContainer';
import useAnalytics from '@/hooks/use-analytics';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  useAnalytics({
    pathname: '/',
    pageTitle: 'Michael Sofayo - Home Page'
  });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className}`}>
        <Box
          aria-label="home-content"
          sx={{ ml: { xs: 0, sm: 0 } }}
          px={{ xs: 3, md: 8 }}>
          <CenteredFlexContainer
            minHeight="100vh"
            width="100%"
            maxWidth={900}
            mx="auto">
            <PrimaryLogo />

            <Typography variant="h3" my={4}>
              Hi there, I&apos;m Michael Sofayo!
            </Typography>

            <Typography variant="body2" align="center" fontSize="1rem">
              My website is still pretty much laying its bricks right now. If
              you&apos;d like to reach out to me, please email{' '}
              <a href="mailto:olumidesofayo@yahoo.co.uk">
                olumidesofayo@yahoo.co.uk
              </a>{' '}
            </Typography>
          </CenteredFlexContainer>
        </Box>
      </main>
    </>
  );
}
